### ISSUE TITLE
io::read_max always returns an empty array

### ISSUE THREAD

**Issue by Squirrelcoding** [esp-rs/embedded-svc#22]
I was investigating another issue in the [esp32 std demo](https://github.com/ivmarkov/rust-esp32-std-demo/issues/103) and this seems to be the problem. Judging by the code, this is what happens:
1. Initiate `offset` and `size` variables
2. Read some data into the buffer
3. break the loop since `size` is 0 and not manipulated yet
4. Return the buffer up until the index `size`, which is 0. This makes the function always return an empty array

```rs
pub fn read_max<R: Read>(mut read: R, buf: &mut [u8]) -> Result<(&[u8], usize), R::Error> {
    let mut offset = 0;
    let mut size = 0;

    loop {
        let r = read.read(&mut buf[offset..])?;

        if size == 0 {
            break;
        }

        offset += r;
        size += r;
    }

    Ok((&buf[..size], size))
}
```

I couldn't find the code in this repo but its [right here](https://docs.rs/embedded-svc/0.22.0/src/embedded_svc/io.rs.html#7-23) on docs.rs

**Comment by ivmarkov** [comment]
As mentioned in the other thread, the function is buggy, but the bug is fixed in `master`. And the function is renamed.
