### ISSUE TITLE
Session handling / middleware / login how to

### ISSUE THREAD

**Issue by mohs8421** [esp-rs/embedded-svc#30]
I would like to add some minimal security to my esp-based http server, I see that embedded-svc provides some utilities to achieve that goal, but it is hard to understand how I have to put these pieces together to achieve my goal. A short tutorial or other kind of documentation on this would be nice.

**Comment by ivmarkov** [comment]
This library just exposes traits and nothing else. A better place to put examples would be the `esp-idf-svc` library.

Other than that, you can join the [Matrix chat](https://app.element.io/#/room/#esp-rs:matrix.org) and ask for help there.
