### ISSUE TITLE
derive EnumVariantNames

### ISSUE THREAD

**Issue by ImUrX** [esp-rs/embedded-svc#34]
It gives a **const** VARIANT in the enum, which will help for doing const code related to configuration

**Comment by ivmarkov** [comment]
You need to further elaborate on what enums you want this an why (as in concrete cases and examples).

**Comment by ImUrX** [comment]
Sorry, I want to make the ``ClientConfiguration`` from the ``wifi`` crate be configured in compile-time.
I'm currently using ``strum``, I thought of directly giving the env to the enum's method but ``from_str`` isnt const.
So I need to use the ``VARIANTS`` const to get all of the variants and also just noticed that the struct would also require derivation of  ``FromRepr`` also

**Comment by ImUrX** [comment]
The precise enum I need is ``AuthMethod`` of the ``wifi`` module, sorry kind of lost in thought currently

**Comment by ivmarkov** [comment]
Can you file a PR with the requested change, so that I can see how it looks in practice, and think where else we can apply it?

**Comment by ImUrX** [comment]
Sure, I will make a PR when I can
