### ISSUE TITLE
No HTTP module in v0.24

### ISSUE THREAD

**Issue by profabe** [esp-rs/embedded-svc#43]
Just tried to leverage the HTTP module on my ESP32 C3, but seems it is not included in embedded-sev v0.24. Also the [documentation](https://docs.rs/embedded-svc/0.24.0/embedded_svc/) doesn't outline it. What am I doing wrong? FYI, using an Espressif ESP32 C3 Rust Developer Board.

<img width="774" alt="Screenshot 2023-03-07 at 23 15 56" src="https://user-images.githubusercontent.com/120320931/223566638-9e17c817-20f9-40ef-8402-e2065462923a.png">

**Comment by ivmarkov** [comment]
Enable the `experimental` feature.
