### ISSUE TITLE
rewrite tait's usage to async fn 

### ISSUE THREAD

**Issue by Vollbrecht** [esp-rs/embedded-svc#49]
upstream changes in embedded-io use 
#![cfg_attr(feature = "nightly", feature(async_fn_in_trait, impl_trait_projections))]
#![cfg_attr(feature = "nightly", allow(incomplete_features))]
instead of 
#![cfg_attr(feature = "nightly", feature(type_alias_impl_trait))]

relevant release https://github.com/embassy-rs/embedded-io/commit/1984b6166f38a12f7f9a6941572585c37ccb87a9

**Comment by ivmarkov** [comment]
Fixed.
