### ISSUE TITLE
How to send async http request?

### ISSUE THREAD

**Issue by lz1998** [esp-rs/embedded-svc#62]
```rust
    let mut cli = embedded_svc::http::client::asynch::Client::wrap(
        esp_idf_svc::http::client::EspHttpConnection::new(
            &esp_idf_svc::http::client::Configuration::default(),
        )
        .unwrap(),
    );
    let result = cli.get("https://ifconfig.co/json").await;
    log::info!("{result:?}");
```

```bash
100 | pub struct EspHttpConnection {
    | ----------------------------
    | |
    | doesn't satisfy `_: Connection`
    | doesn't satisfy `_: Read`
    | doesn't satisfy `_: Write`
    |

```

**Comment by Vollbrecht** [comment]
sorry this is not a direct answer to your question, but if you are looking for one big async project where many of the presented stuff from here  and from esp-idf-hal/svc is used have a look in [this project ](https://github.com/ivmarkov/ruwm)

**Comment by lz1998** [comment]
> sorry this is not a direct answer to your question, but if you are looking for one big async project where many of the presented stuff from here and from esp-idf-hal/svc is used have a look in [this project ](https://github.com/ivmarkov/ruwm)

There isn't an async http client in `ruwm`.

Is it possible to get a TcpStream which implement `io::{asynch::Read, asynch::Write}`. I am trying to send async http request.

**Comment by lz1998** [comment]
What should the param be in `embedded_svc::http::client::asynch::Client::wrap()`?

**Comment by Vollbrecht** [comment]
For one implementation of the client api see [edge-net](https://github.com/ivmarkov/edge-net) as ivmarkov pointed to. Though as per description need's some fixing

**Comment by ivmarkov** [comment]
[Yes](https://github.com/ivmarkov/rust-esp32-std-demo/blob/main/src/main.rs#L721). Again: can you join the Matrix room? Issues are not supposed to serve as a Help forum.
