### ISSUE TITLE
ESP32-C3 disconnecting after starting Wi-Fi

### ISSUE THREAD

**Issue by weiying-chen** [esp-rs/embedded-svc#73]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

My ESP32-C3 disconnects when I add this Rust code (note: there are no errors whatsoever):

    use embedded_svc::wifi::{ClientConfiguration, Configuration, Wifi};

    let mut wifi_driver = EspWifi::new(peripherals.modem, sys_loop, Some(nvs)).unwrap();
    wifi_driver.start().unwrap(); // more specifically, this line

This is what espmonior sees before my ESP32-C3 disconnects from my mini PC:

```
I (500) wifi:wifi firmware version: 1ba8b6a
I (500) wifi:wifi certification version: v7.0
I (500) wifi:config NVS flash: enabled
I (500) wifi:config nano formating: disabled
I (510) wifi:Init data frame dynamic rx buffer num: 32
I (510) wifi:Init management frame dynamic rx buffer num: 32
I (520) wifi:Init management short buffer num: 32
I (520) wifi:Init dynamic tx buffer num: 32
I (530) wifi:Init static tx FG buffer num: 2
I (530) wifi:Init static rx buffer size: 1600
I (530) wifi:Init static rx buffer num: 10
I (540) wifi:Init dynamic rx buffer num: 32
I (540) wifi_init: rx ba win: 6
I (550) wifi_init: tcpip mbox: 32
I (550) wifi_init: udp mbox: 6
I (550) wifi_init: tcp mbox: 6
I (560) wifi_init: tcp tx win: 5744
I (560) wifi_init: tcp rx win: 5744
I (570) wifi_init: tcp mss: 1440
I (570) wifi_init: WiFi IRAM OP enabled
I (570) wifi_init: WiFi RX IRAM OP enabled
I (585) phy_init: phy_version 1150,7c3c08f,Jan 24 2024,17:32:21
Device disconnected; exiting
```

[This](https://gist.github.com/rajeshpachaikani/2ef7c11b4d7e8a6704dba0f323bcdd6d) is the full code.

Also posted [here](https://github.com/espressif/esp-idf/issues/13157).

**Comment by ivmarkov** [comment]
I strongly suggest 
(a) you update your crates - you are using outdated `esp-idf-svc`
(b) start with [this example](https://github.com/esp-rs/esp-idf-svc/blob/master/examples/wifi.rs), as your code has issues

**Comment by weiying-chen** [comment]
@ivmarkov I cloned that repository I set the WIFI_SSID and WIFI_PASS environment variables. Then I ran the wifi example as instructed: `$ MCU=esp32c3 cargo espflash flash --target riscv32imc-esp-espidf --example wifi --monitor`.

No compiling errors. But I'm getting the same result plus a `× Broken pipe` message:

```
I (746) wifi_init: rx ba win: 6
I (746) wifi_init: tcpip mbox: 32
I (756) wifi_init: udp mbox: 6
I (756) wifi_init: tcp mbox: 6
I (766) wifi_init: tcp tx win: 5744
I (766) wifi_init: tcp rx win: 5744
I (766) wifi_init: tcp mss: 1440
I (776) wifi_init: WiFi IRAM OP enabled
I (776) wifi_init: WiFi RX IRAM OP enabled
I (806) phy_init: phy_version 1130,b4e4b80,Sep  5 2023,11Error:   × Broken pipe
```

Full log [here](https://gist.github.com/weiying-chen/9a0cf17853d879dcc501a49e6f067fc4).

**Comment by ivmarkov** [comment]
Given that it works for everybody else, you are likely having a hardware problem. As in your device is underpowered.

**Comment by weiying-chen** [comment]
@ivmarkov I see. So what do you suggest I do?

**Comment by ivmarkov** [comment]
Try using a more powerful usb-a slot/hub that can actually deliver enough power to the board.

**Comment by ivmarkov** [comment]
Glad that you got it working!

As for why the log did not tell you - I don't know. My assumption is that the [ESP IDF brownout detector](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-guides/fatal-errors.html#brownout) is just a "best effort" feature, which is not always guaranteed to work...

**Comment by kamnxt** [comment]
for what it's worth, on a "SuperMini" ESP32-C3 board, I was able to get a connection just about instantly after adding a 
```
    unsafe{esp_wifi_set_max_tx_power(34)};
```
after the call to `wifi.connect()`, just like in the proposed fix on the Tasmota issue about some ESP32-C3 boards not connecting to WiFi: https://github.com/arendst/Tasmota/discussions/15443

**Comment by weiying-chen** [comment]
@kamnxt Thanks a lot, it works (I had Wi-Fi/power issues again)! Do  you know how does that line fixe the issue?

**Comment by kamnxt** [comment]
@weiying-chen This just limits the maximum WiFi transmission power of the ESP32-C3, to 8dBm. You can find the entire range of supported values here: https://github.com/espressif/esp-idf/blob/b15cfab6f357a3239dc6ccdbd61c2f7f9aedd969/components/esp_wifi/include/esp_wifi.h#L1005

Without this, it uses the default power (probably maximum, 20dBm?). My guess is that the board you are using either has bad antenna matching (causing higher power draw than normal) or the 3.3V voltage regulator is too weak. Either way it is causing the voltage to drop and the chip behaves incorrectly.

Note that using this solution also causes your WiFi range to be reduced. You can try different values (check the link I mentioned) and see how high you can set it before things stop working again.

**Comment by weiying-chen** [comment]
@kamnxt Sometimes it starts successfully,

```
I (664) rust_esp32c3_hx711: Wifi started
```

Sometimes it doesn't start successefully:

```
I (614) wifi_init: WiFi RX IRAM OP enabled
Device disconnected; exiting 
```

Is this normal, and I have to keep polling until it connects? Or my ESP32-C3 is faulty as you said?

**Comment by kamnxt** [comment]
Not sure, the board I am using failed in a different way - it would report a `ESP_ERR_TIMEOUT`. What power settings / set_tx_power values have you tried?

**Comment by weiying-chen** [comment]
I tried  `unsafe { esp_wifi_set_max_tx_power(34) };`. This is the most stable one. `unsafe { esp_wifi_set_max_tx_power(34) };` didn't connect to Wi-Fi. I think a few times I connected to Wi-Fi without `esp_wifi_set_max_tx_power`.

I can't see a pattern. The only pattern is the one I mentioned: if it connects once to Wi-Fi, then it'll connect again (if I run the program again). Then if I disconnect stuff, the randomness will come back.
