### ISSUE TITLE
Wifi ClientConfiguration options

### ISSUE THREAD

**Issue by embediver** [esp-rs/embedded-svc#74]
I noticed that the `wifi::ClientConfiguration` is lacking multiple features which are available for the esp-idf sta config.

Following is a list of (possibly incomplete) missing features:
- Support for scan method and sort order
  - Scan method: complete scan, or stop at first match
  - Sort method to select AP to connect to after a complete scan
- Protected Management Frame (PMF) configuration
- BSS transition management
- Multi Band Operation (MBO) setting(s)

I didn't investigate which features are available on other devices and probably some of the above listed are missing or implemented differently on other devices.

Can we implement some of these in the ClientConfiguration and where are possible problems?
I would personally like to see some option to set the scan and sort method since they can cause significant differences on how long a connect takes. But probably they are also the least generic options of the listed.

BSS transition capability and PMF capability are no big problem to add in my opinion.

**Comment by ivmarkov** [comment]
The best way to get some of these implemented is to start working on PR(s). :)

**Comment by embediver** [comment]
Here you go #75
